name: rentpulse
version: "1.0.0"
config-version: 2

profile: rentpulse

model-paths: ["models"]
macro-paths: ["macros"]

models:
  rentpulse:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: table
    marts:
      +schema: analytics
      +materialized: table
